### ISSUE TITLE
landing_page_spec failing test

### ISSUE THREAD

**Issue by devonwigle** [Shared-Milk/shared-milk-ui#103]
This test is failing `should be able to navigate to the Need Milk page view on desktop or mobile`
![Screen Shot 2022-04-03 at 11 24 21 AM](https://user-images.githubusercontent.com/88619501/161437792-5352a5d2-8605-44aa-bbe3-595ce36b6877.png)

Would also recommend separating mobile check from desktop check, since they are checking different screen sizes.

**Comment by janitastic** [comment]
I can take this one. I'll try to split mobile and desktop views.

**Comment by janitastic** [comment]
Fixed it! I split up the desktop tests and mobile tests to clean this up. Everything is passing now.
