### ISSUE TITLE
Write Cypress Tests

### ISSUE THREAD

**Issue by janitastic** [Shared-Milk/shared-milk-ui#39]
- [x] Header & Footer - _move these to a separate integration file_
- [x] Home Page - @cagallo 
   - [x] Buttons
- [x] Need Milk
   - [x] Donor Card
   - [x] Confirmation Message
- [x] Donate Milk
    - [x] Donate Milk Form
- [x] Donor Sorry
- [x] Donor Thank You
- [x] About Us
- [x] Support
- [x] Milk Request Form

**Comment by janitastic** [comment]
@cagallo completed home page testing

**Comment by devonwigle** [comment]
completed support page

**Comment by janitastic** [comment]
I updated the "task" checkboxes in the description so one of us can take on moving the header and footer tests to a separate integration file.

**Comment by devonwigle** [comment]
Submitted PR for most of donate milk form paths, needs revisit once error handling complete

**Comment by devonwigle** [comment]
Header and footer tests complete

**Comment by janitastic** [comment]
@devonwigle I updated the landing-page test. You'll want to git pull and merge main again to revisit your header and footer tests.
